### ISSUE TITLE
Installing android application on windows platform

### ISSUE THREAD

**Issue by amarpulli1994** [ghzmdr/Panic-Button#2]
Hello,
Now your android application is working in my device, but we want install your application on windows platform. Any suggestions is there? How I will run my android application on windows platform?Please help me...
Thanks and Regards,
Amar.

**Comment by vinzdef** [comment]
I personally use Genymotion as an Android emulator, there are many other.

However, this is not the place to discuss how to run Android on Windows. 
Refrain from posting such questions.
